export const USER_SERVICE = Symbol('USER_SERVICE');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const FEEDBACK_SERVICE = Symbol('FEEDBACK_SERVICE');

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const FEEDBACK_REPOSITORY = Symbol('FEEDBACK_REPOSITORY');
export const FEEDBACK_ATTACHMENT_REPOSITORY = Symbol('FEEDBACK_ATTACHMENT_REPOSITORY');

export const IS_PUBLIC_KEY = 'isPublic';